export const userType = {
  SET_ADMIN_ID: 'SET_ADMIN_ID',
  SET_ADMIN_AVATAR: 'SET_ADMIN_AVATAR',
  SET_ADMIN_NAME: 'SET_ADMIN_NAME',
}

export const cacheType = {
  SET_CACHE_VIEW_DATA: 'SET_CACHE_VIEW_DATA'
}

export const ossType = {
  SET_CACHE_OSS_DATA: 'SET_CACHE_OSS_DATA'
}

export const permissionType = {
  SET_PERMISSION_CACHE: 'SET_PERMISSION_CACHE',
  SET_PERMISSION: 'SET_PERMISSION',
  SET_ROUTERS: 'SET_ROUTERS'
}

export const appType = {
  TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR',
  SIDEBAR_STATUS: 'SIDEBAR_STATUS',
  OPEN_SIDEBAR: 'OPEN_SIDEBAR',
  CLOSE_SIDEBAR: 'CLOSE_SIDEBAR',
  TOGGLE_DEVICE: 'TOGGLE_DEVICE',
  PAGE_LOADING: 'PAGE_LOADING',
  SET_LANGUAGE: 'SET_LANGUAGE',
  SET_THEME: 'SET_THEME',
  SET_DESKTOP_NAV_WIDTH: 'SET_DESKTOP_NAV_WIDTH',
  SET_DEVICE_NAV_WIDTH: 'SET_DEVICE_NAV_WIDTH',
  SET_VARY_WIDTH: 'SET_VARY_WIDTH'
}

export const tagsViewType = {
  ADD_VISITED_VIEWS: 'ADD_VISITED_VIEWS',
  DEL_VISITED_VIEWS: 'DEL_VISITED_VIEWS',
  DEL_OTHERS_VIEWS: 'DEL_OTHERS_VIEWS',
  DEL_ALL_VIEWS: 'DEL_ALL_VIEWS'
}

export const errorLogType = {
  ADD_ERROR_LOG: 'ADD_ERROR_LOG'
}

export const systemType = {
  SET_MARK: 'SET_MARK'
}
